import os
from dotenv import load_dotenv
# Core replacement: use deepseek integration
from langchain_deepseek import ChatDeepSeek
from langchain_openai import ChatOpenAI
from langchain_classic import hub
from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.tools import StructuredTool, Tool

# 1. Load environment variables (ensure DEEPSEEK_API_KEY is in your .env)
load_dotenv()

# --- Define tool functions (Logic) ---

def greet_user(name: str) -> str:
    """Greet the user by name."""
    return f"Hello, {name}!"

def reverse_string(text: str) -> str:
    """Reverse the given string."""
    return text[::-1]

def concatenate_strings(a: str, b: str) -> str:
    """Concatenate two strings."""
    return a + b

# 2. Create tool list
# DeepSeek is perfectly capable of parsing complex Schemas generated by StructuredTool
tools = [
    Tool(
        name="GreetUser",
        func=greet_user,
        description="Greet the user by name.",
    ),
    Tool(
        name="ReverseString",
        func=reverse_string,
        description="Reverse the given string.",
    ),
    # Use StructuredTool to handle functions with multiple parameters
    StructuredTool.from_function(
        func=concatenate_strings,
        name="ConcatenateStrings",
        description="Concatenate two strings, a and b, together.",
    ),
]

# 3. Initialize the DeepSeek model
# Using deepseek-chat (which is DeepSeek-V3)
#llm = ChatDeepSeek(
#    model="deepseek-chat", 
#    temperature=0  # It is recommended to set temperature to 0 for tool calling to ensure parameter accuracy
#)
llm = ChatOpenAI(
    model="gpt-4o-mini",
    # base_url is optional here; defaults to https://api.openai.com/v1
)

# 4. Pull the specialized Prompt for tool calling from the Hub
# Although named openai-tools-agent, it is a standard template compatible with DeepSeek's tool calling format
prompt = hub.pull("hwchase17/openai-tools-agent")

# 5. Create the tool-calling agent
agent = create_tool_calling_agent(
    llm=llm,
    tools=tools,
    prompt=prompt,
)

# 6. Create the executor
agent_executor = AgentExecutor.from_agent_and_tools(
    agent=agent,
    tools=tools,
    verbose=True,               # Enable detailed logs to observe DeepSeek's decision chain
    handle_parsing_errors=True, # Gracefully handle parsing errors
)

# 7. Test interaction
print("\n--- OpenAI Structured Tool Agent Started ---")

# Test single-parameter tool
res1 = agent_executor.invoke({"input": "Greet Mindy Jen"})
print("Response 1:", res1["output"])

# Test complex multi-parameter tool
res2 = agent_executor.invoke({"input": "Put the words 'Hello' and 'World' together"})
print("Response 2:", res2["output"])

# Test logical combination
res3 = agent_executor.invoke({"input": "First reverse the string 'OpenAI', then greet the reversed result"})
print("Response 3:", res3["output"], '\n')