import os
from dotenv import load_dotenv
from langchain_deepseek import ChatDeepSeek
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableLambda, RunnableSequence

# 1. Load environment variables (must include DEEPSEEK_API_KEY)
load_dotenv()

# 2. Initialize DeepSeek model
#model = ChatDeepSeek(model="deepseek-chat")
model = ChatOpenAI(
    model="gpt-4o-mini",
    # base_url is optional here; defaults to https://api.openai.com/v1
)

# 3. Define Prompt Template (System + Human structure)
prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a master of deadpan humor specialized in telling jokes about {topic}."),
        ("human", "Please tell {joke_count} jokes."),
    ]
)

# 4. Create independent execution units (Runnable Steps)
# These steps correspond to each transformation of data as it flows through the chain

# Step A: Formatting - Converts the dictionary into a PromptValue
format_prompt = RunnableLambda(lambda x: prompt_template.format_prompt(**x))

# Step B: Model Invocation - Passes messages to DeepSeek (using to_messages to ensure correct format)
invoke_model = RunnableLambda(lambda x: model.invoke(x.to_messages()))  # type: ignore

# Step C: Output Parsing - Extracts the text content from the AIMessage
parse_output = RunnableLambda(lambda x: x.content)  # type: ignore

# 5. Construct RunnableSequence (Equivalent to the pipe operator chain in LCEL)
# Explicitly specify: Start (first), Intermediate steps (middle list), End (last)
chain = RunnableSequence(first=format_prompt, middle=[invoke_model], last=parse_output)

# 6. Run the Chain
# The input dictionary will pass through format_prompt -> invoke_model -> parse_output in sequence
response = chain.invoke({"topic": "programmers", "joke_count": 2})

# 7. Output final results
print("\n----- Deadpan jokes generated by OpenAI -----\n")
print(response, '\n')